### PR TITLE
gracefully close test kafka ports

### PR DESCRIPTION
**Pull request by jamescway**
Kafka ports are not getting closed properly, this makes an attempt to close gracefully, thus not leading the port in a weird state.

*Do not review, this is being tested in travis!*

### CODE REVIEW

**Comment by rtyler** [comment]
```
[info] All tests passed.
[info] Passed: Total 26, Failed 0, Errors 0, Passed 26
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/travis/.ivy2/cache/org.slf4j/slf4j-jdk14/jars/slf4j-jdk14-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/travis/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
[info] + /config should
[info]   + validate query configs
[info]     + query-dev6407834719414164002.scala
[info]     + query-cassandra9187775970419432255.scala
[info] Passed: Total 4, Failed 0, Errors 0, Passed 4
[info] + /config should
[info]   + validate collector configs
[info]     + collector-dev3501241333079093356.scala
[info]     + collector-hbase8095403111594286920.scala
[info]     + collector-cassandra8495964067347995657.scala
[info] Passed: Total 5, Failed 0, Errors 0, Passed 5
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```


@jamescway those `close()` calls won't block forever for any case will they?

**Comment by eirslett** [comment]
If we want to guard against blocking builds, we could wrap it in Future { ... } and then use Await.result with a timeout?

**Comment by adriancole** [comment]
> If we want to guard against blocking builds, we could wrap it in Future {
... } and then use Await.result with a timeout

Or whatever the test's version of a timeout concept is. Ex
https://github.com/junit-team/junit/wiki/Timeout-for-tests

**Comment by eirslett** [comment]
touché

**Comment by jamescway** [comment]
@rtyler it seems like it could be blocking ([javadoc source](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/net/ServerSocket.java#ServerSocket.close%28%29)), not sure about forever.

Sounds good on the timeout, I'm no longer convinced this is the solution, needs more testing with the openzipkin build, was working pretty good on our fork O_o.

**Pull request closed without merging**
